### ISSUE TITLE
카카오 로그인 연동

### ISSUE THREAD

**Issue by jin-park0115** [triptalk-4/triptalk-frontend#237]
@oinochoe 멘토님 카카오 로그인 연동 테스트를 할때 
백엔드 분 께서 redirect-Uri 를 저희 베포사이트 주소로 하셨는데 
이 redirect-Uri 를 로컬 서버로 해서 테스트를 해볼수는 없나여?

`const KakaoLogin = () => {
  const REST_API_KEY = 'c5e7d3418384adeea868cb7470027a67';
  const REDIRECT_URI = 'https://triptalk.vercel.app/auth';
  const link = `https://kauth.kakao.com/oauth/authorize?client_id=${REST_API_KEY}&redirect_uri=${REDIRECT_URI}&response_type=code`;

  const handleKakaoLogin = () => {
    window.location.href = link;
  };

  return (
    <Kakao onClick={handleKakaoLogin}>
      <TbMessageCircle />
    </Kakao>
  );
};

export default KakaoLogin;

const Kakao = styled.div`
  width: 50%;
  font-size: 22px;
  font-weight: 500;
  background-color: #fee500;
  border-radius: 10px;
  height: 60px;
  line-height: 60px;
  margin-bottom: 32px;
  cursor: pointer;
  border: none;
  &:focus {
    outline: none;
  }
`;
`
이렇게 uri 를 설정을 해놓은 상태 이기는 합니다. 베포사이트는 저렇게 수정 전 코드여서 테스트 해보기가 어렵습니다.

**Comment by oinochoe** [comment]
> @oinochoe 멘토님 카카오 로그인 연동 테스트를 할때 백엔드 분 께서 redirect-Uri 를 저희 베포사이트 주소로 하셨는데 이 redirect-Uri 를 로컬 서버로 해서 테스트를 해볼수는 없나여?
> 
> `const KakaoLogin = () => { const REST_API_KEY = 'c5e7d3418384adeea868cb7470027a67'; const REDIRECT_URI = 'https://triptalk.vercel.app/auth'; const link = `[https://kauth.kakao.com/oauth/authorize?client_id=${REST_API_KEY}&redirect_uri=${REDIRECT_URI}&response_type=code`](https://kauth.kakao.com/oauth/authorize?client_id=$%7BREST_API_KEY%7D&redirect_uri=$%7BREDIRECT_URI%7D&response_type=code%60);
> 
> const handleKakaoLogin = () => { window.location.href = link; };
> 
> return ( ); };
> 
> export default KakaoLogin;
> 
> const Kakao = styled.div`width: 50%; font-size: 22px; font-weight: 500; background-color: #fee500; border-radius: 10px; height: 60px; line-height: 60px; margin-bottom: 32px; cursor: pointer; border: none; &:focus { outline: none; }`; ` 이렇게 uri 를 설정을 해놓은 상태 이기는 합니다. 베포사이트는 저렇게 수정 전 코드여서 테스트 해보기가 어렵습니다.

@jin-park0115 redirect_uri에 추가적으로 여러분의 환경을 전송해서 다시 받아서 보는 방법도 있습니다. 

&environment=development
또는
&environment=production
이런식으로 가능하겠지요.

해당 파라미터를 추가해서 보내주시고 구현해달라고 하면됩니다.

**Comment by jin-park0115** [comment]
아.. 파라미터에 추가하고 어떤식으로 구현해달라고 해야할지.. 
한번 말해 보겠습니다

**Comment by oinochoe** [comment]
@jin-park0115 해결되셨나요?

**Comment by jin-park0115** [comment]
이미지 파일을 어떻게 올리는지 모르겠어서 슬랙으로 남겼습니다!

**Comment by oinochoe** [comment]
음 vercel.json에 대해서 공부하셔야합니다! @jin-park0115

**Comment by jin-park0115** [comment]
넵!
