### ISSUE TITLE
카카오 지도 관련 이슈

### ISSUE THREAD

**Issue by leesh2985** [triptalk-4/triptalk-frontend#24]
![캡쳐3](https://github.com/triptalk-4/triptalk-frontend/assets/127204694/9a5e55b7-e0cd-4e4a-98db-e066a16c1f73)

진님이 카카오지도 api를 작업해서 올려주셨는데 진님 화면에는 이렇게 보이는데 제화면에는 
![image](https://github.com/triptalk-4/triptalk-frontend/assets/127204694/8152b83a-0e33-48dc-b231-6d7296626e93)
빈화면으로 보여요 혹시몰라 라이브러리도 다운받았는데 변하지도 않네요...

@oinochoe

**Comment by jin-park0115** [comment]
[
![캡쳐4](https://github.com/triptalk-4/triptalk-frontend/assets/122075848/07671c54-d94d-44ae-beff-2952cd8789c8)
](url)
이거는 카카오 Develop 에서 사이트 도메인을 제 npm run dev 해서 나온 local 주소를 붙여넣었습니다.

**Comment by oinochoe** [comment]
.vscode에 host도 정해서 사용해보세요.
@jin-park0115 @leesh2985

**Comment by leesh2985** [comment]
host를 정하는게 https://iamfreeman.tistory.com/entry/%EC%9C%88%EB%8F%84%EC%9A%B0-hosts-%ED%8C%8C%EC%9D%BC-%EC%88%98%EC%A0%95%ED%95%98%EA%B8%B0-%EC%9C%88%EB%8F%84%EC%9A%B0-%EB%A6%AC%EB%88%85%EC%8A%A4-%ED%8F%AC%ED%95%A8 이거인가요??

**Comment by leesh2985** [comment]
https://poalim.tistory.com/19 
![image](https://github.com/triptalk-4/triptalk-frontend/assets/127204694/77063cb4-df33-4267-adac-2e02308e3d6f)
![image](https://github.com/triptalk-4/triptalk-frontend/assets/127204694/aaf7ebed-0c7b-4deb-8a14-7f8929521040)
여기 host를 변경하는 건가요??
@oinochoe

**Comment by oinochoe** [comment]
@jin-park0115 @leesh2985 아뇨 .vscode의 settings.json이요

**Comment by leesh2985** [comment]
![image](https://github.com/triptalk-4/triptalk-frontend/assets/127204694/39554905-ace9-4fd5-8ca4-a2030548ab1a)
여기서 하는 건가요?? 그러면 개인 vs에서 하게되면 다른분들은 못보게 되는거아닌가요?
@oinochoe

**Comment by oinochoe** [comment]
개인말고 루트경로에 제가 .vscode폴더에 settings.json이라고 말씀드렸어요

**Comment by jin-park0115** [comment]
넵 알겠습니다! 감사합니다!

**Comment by leesh2985** [comment]
넵 해결했습니다!
