### ISSUE TITLE
vercel 배포 질문

### ISSUE THREAD

**Issue by jin-park0115** [triptalk-4/triptalk-frontend#258]
@oinochoe 
멘토님 저희가 지금 vercel로 배포를 하였는데 배포는 다 됐는데 이제 배포 사이트로 가서 로그인을 하고 메인으로 가면 이런 오류가 뜨는데
[
![질문1](https://github.com/triptalk-4/triptalk-frontend/assets/122075848/c2be2cb8-6886-49be-8b73-acbb90925187)
](url)
혹시 저희가 api들이 환경변수로 해놓아야 할지 궁금합니다.

`const MAIN_REST_API_KEY = import.meta.env.VITE_REACT_APP_MAIN_API;`
` const response = await axios.post(`${MAIN_REST_API_KEY}/api/users/login`, {
        email: userEmail,
        password: password,
      });`
      
      로그인은 환경변수를 써서 사용했더니 로그인은 잘 되고 다른 api 호출들은 환경변수를 안했습니다.

**Comment by oinochoe** [comment]
@jin-park0115 network를 확인하시면 왜 잘못불러오고 있는지 알 수 있습니다.
proxy는 개발 모드에서만 적용하셔야하고, 배포시에는 proxy를 적용하시면 안됩니다.
vite의 mode를 가져와서 개발모드에서만 proxy를 설정하도록 하세요.

**Comment by jin-park0115** [comment]
넵 감사합니다

**Comment by jin-park0115** [comment]
[
![proxy캡쳐](https://github.com/triptalk-4/triptalk-frontend/assets/122075848/f0364112-1db6-4cdd-b8a4-4d60251beaeb)
](url)
이렇게 하면 될까요??

**Comment by oinochoe** [comment]
@jin-park0115 아뇨 definedConfig 안에 객체 { ... } 를 return 해주는 방식으로 해주시면 됩니다.

**Comment by jin-park0115** [comment]
`mport { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

const isDevelopment = process.env.NODE_ENV === 'development';
// https://vitejs.dev/config/
const developmentProxy = {
  '/address': {
    target: 'https://triptalk.xyz',
    changeOrigin: true,
    rewrite: path => path.replace(/^\/address/, ''),
    secure: false,
    ws: true,
  }
}

export default defineConfig({
  plugins: [react()],
  server: {
    proxy: isDevelopment ? developmentProxy : {},
    port: 3000,
  },

  build: {
    rollupOptions: {
      output: {
        manualChunks: undefined,
      }
    }
  }
});`
이렇게 맞을까요...?

**Comment by oinochoe** [comment]
@jin-park0115 넵 잘 하셨네요!
이렇게 따로 관리하셔도 좋습니다.

```js

// vite.config.ts
import { defineConfig } from 'vite';

const productionConfig = {
  // production 환경에 대한 설정
};

const developmentConfig = {
  // development 환경에 대한 설정
  server: {
    proxy: {
      '/api': 'http://localhost:3000',
    },
  },
};

export default defineConfig(({ mode }) => {
  return mode === 'development' ? developmentConfig : productionConfig;
});

```

**Comment by jin-park0115** [comment]
아하... 넵 감사합니다!
