### ISSUE TITLE
이미지 위 글 이슈

### ISSUE THREAD

**Issue by leesh2985** [triptalk-4/triptalk-frontend#32]
![image](https://github.com/triptalk-4/triptalk-frontend/assets/127204694/0c3c572d-2f37-4e52-ac07-4c36b801b637)
const ImgContainer = styled.div`
  padding: 30px;
  position: relative;
`;
const TextDiv = styled.div`
  position: absolute;
  display: grid;
  justify-items: stretch;
  text-align: center;
  grid-template-columns: 1fr 1fr;
  grid-template-rows: 1fr 1fr;
  bottom: 0;
  width: 320px;
`;
이미지위에 글을 보이게 하고싶어서 position을 줬는데 이미지처럼 왜 이미지밖으로 나올까요?? 그리고 그라데이션을 줬는데 왜 화면에는 보이지 않을까요???

const TravelImg = styled.img`
  width: 100%;
  height: 100%;
  object-fit: cover;
  background: linear-gradient(black, yellow); // 그라데이션 test
`;
![image](https://github.com/triptalk-4/triptalk-frontend/assets/127204694/bbb24a41-a10d-4347-b03e-29e59e12f740)

**Comment by leesh2985** [comment]
@oinochoe

**Comment by oinochoe** [comment]
@leesh2985 혹시 라이브러리를 막 수정하시려고 하면 라이브러리의 CSS가 우선하기 때문에 기능이 제대로 동작하지 않을 확률이 큽니다.

라이브러리를 사용하실 때는 최대한 라이브러리 그대로의 옵션들만 이용해서 구현하시기를 추천드립니다.

아니라면 직접 Carousel을 구현하시는 편이 낫습니다.

**Comment by oinochoe** [comment]
@leesh2985 라이브러리를 수정할 때 추천드리는 방법은 전체 라이브러리의 레이아웃이 옮겨지는 부분이거나 그 요소 내부의 요소들만 움직일 때 그 Carousel에 겹쳐진 레이어들을 이동하거나 아이템들을 이동할 때 뿐이지 전체 카드영역인 Carousel 그 자체를 수정하는 것은 추천드리지 않습니다.

**Comment by oinochoe** [comment]
제가 봤을 때 원인은 위의 carousel을 직접적으로 이미 떨어뜨려놨기 때문에 화면이 깨지는 것으로 보입니다.

**Comment by leesh2985** [comment]
넵 다시 수정해보겠습니다
