### ISSUE TITLE
팝업 버튼 위치 이슈

### ISSUE THREAD

**Issue by leesh2985** [triptalk-4/triptalk-frontend#42]
![image](https://github.com/triptalk-4/triptalk-frontend/assets/127204694/63126710-a181-4d5e-9c66-fb8893833508)
밑에 버튼 3개는 중앙에 오게하고싶은데 grid가 아닌 flex를 사용해서 만들어야 하는걸까요??

**Comment by leesh2985** [comment]
@oinochoe

**Comment by oinochoe** [comment]
![image](https://github.com/triptalk-4/triptalk-frontend/assets/24869229/4e118045-c575-4e3a-8de2-94414e22039a)
보통 위와 같은 레이아웃은 일반적으로로 마지막도 좌측정렬하는 것이 좋습니다.

말씀하신대로 마지막 줄의 7개가 안되는 내용에 대해 가운데로 정렬하는 레이아웃을 만들 때는 grid를 사용하려면 마지막 row에 대한 예외처리가 필요하므로 flex 레이아웃이 더 간단합니다.
@leesh2985

**Comment by leesh2985** [comment]
@oinochoe 넵 그대로 진행하겠습니다!
