### ISSUE TITLE
탭기능 이슈

### ISSUE THREAD

**Issue by leesh2985** [triptalk-4/triptalk-frontend#45]
![Animation](https://github.com/triptalk-4/triptalk-frontend/assets/127204694/e85efa46-708a-459e-b0a8-030ca165dc87)
#37 에 [# Feat : 탭기능 추가](https://github.com/triptalk-4/triptalk-frontend/pull/37/commits/8fa328e49cdd0ca569af52030c05e7247d1f1f2d) 부분에서 gif처럼 클릭이 되면 글자색이 유지가 되야하는데 홈이랑 여행지만 유지되고 리뷰맵과 일정은 호버만 됩고 2번정도 클릭하면 유지가 되구요... 왜 반은 되고 반은 안될까요??
@oinochoe

**Comment by oinochoe** [comment]
@leesh2985 이유는 코드를 봐야 잘 알 수 있을 것 같은데, 기본적으로 useParams를 사용해서 해당 부분에 Active 등의 클래스로 활성화한다면 문제 없을 이슈 같습니다.

**Comment by leesh2985** [comment]
![Animation](https://github.com/triptalk-4/triptalk-frontend/assets/127204694/08140b04-e429-463d-8f69-be0dfd81904d)

`import { useEffect, useRef, useState } from 'react';
import styled from 'styled-components';
import Search from './Search/Search';
import { DEFAULT_FONT_COLOR, MAIN_COLOR } from '../color/color';
import { Link } from 'react-router-dom';

interface NavItemProps {
  to: string;
  $isActive: boolean;
}

export default function Header() {
  // const defaultImg = 'https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png';

  const [activeTab, setActiveTab] = useState<string>(localStorage.getItem('activeTab') || '');
  const tabsRef = useRef<HTMLUListElement>(null);

  useEffect(() => {
    const handleOutsideClick = (event: MouseEvent) => {
      if (tabsRef.current && !tabsRef.current.contains(event.target as Node)) {
        setActiveTab('');
      }
    };

    document.body.addEventListener('click', handleOutsideClick);

    return () => {
      document.body.removeEventListener('click', handleOutsideClick);
    };
  }, []);

  const handleTabClick = (tabName: string) => {
    setActiveTab(tabName);
  };

  // 활성 탭이 변경될 때 localStorage에 저장
  useEffect(() => {
    console.log('activeTab:', activeTab);
    localStorage.setItem('activeTab', activeTab);
  }, [activeTab]);

  return (
    <GnbContainer>
      <Gnb>
        <Logo to="/main">
          <LogoImg src="/img/logo.png" alt="로고" />
        </Logo>
        <Avatar to="/myinfo">
          <AvatarImg src="https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png" />
        </Avatar>
      </Gnb>
      <Nav ref={tabsRef}>
        <NavItem to="/main" onClick={() => handleTabClick('home')} $isActive={activeTab === 'home'}>
          홈
        </NavItem>
        <NavItem to="/travel" onClick={() => handleTabClick('travel')} $isActive={activeTab === 'travel'}>
          여행지
        </NavItem>
        <NavItem to="/schedule" onClick={() => handleTabClick('schedule')} $isActive={activeTab === 'schedule'}>
          일정
        </NavItem>
        <NavItem to="/lookmap" onClick={() => handleTabClick('lookmap')} $isActive={activeTab === 'lookmap'}>
          리뷰맵
        </NavItem>
        <Search />
      </Nav>
    </GnbContainer>
  );
}` 일정부분만 저렇게 이전에 클릭한 정보가 console.log에 뜨는거 같아요.. @oinochoe

**Comment by oinochoe** [comment]
@leesh2985 활성화하기 위해서 불필요한 코드가 너무 많아서 이렇게 수정하세요.

```javascript
import { useRef } from 'react';
import styled from 'styled-components';
import Search from './Search/Search';
import { DEFAULT_FONT_COLOR, MAIN_COLOR } from '../color/color';
import { Link, useLocation } from 'react-router-dom';

interface NavItemProps {
  $isActive: boolean;
}

export default function Header() {
  // const defaultImg = 'https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png';

  const tabsRef = useRef<HTMLUListElement>(null);
  const location = useLocation();

  return (
    <GnbContainer>
      <Gnb>
        <Logo to="/main">
          <LogoImg src="/img/logo.png" alt="로고" />
        </Logo>
        <Avatar to="/myinfo">
          <AvatarImg src="https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png" />
        </Avatar>
      </Gnb>
      <Nav ref={tabsRef}>
        <NavItem to="/main" $isActive={location.pathname === '/main'}>
          홈
        </NavItem>
        <NavItem to="/travel"  $isActive={location.pathname === '/travel'}>
          여행지
        </NavItem>
        <NavItem to="/schedule"  $isActive={location.pathname === '/schedule'}>
          일정
        </NavItem>
        <NavItem to="/lookmap"  $isActive={location.pathname === '/lookmap'}>
          리뷰맵
        </NavItem>
        <Search />
      </Nav>
    </GnbContainer>
  );
}

const GnbContainer = styled.div`
  display: grid;
  grid-template-rows: 1fr 1fr;
  align-items: center;
  height: auto;
`;

const Gnb = styled.div`
  display: flex;
  justify-content: flex-end;
  align-items: center;
  padding: 20px 55px 15px;
  border-bottom: 1px solid #c1c1c1;
`;

const Logo = styled(Link)`
  display: flex;
  align-items: center;
  padding-right: 400px;
  cursor: pointer;
`;

const LogoImg = styled.img`
  width: 200px;
  height: auto;
`;

const Avatar = styled(Link)`
  height: 50px;
`;

const AvatarImg = styled.img`
  width: 50px;
  height: 50px;
  border-radius: 100%;
`;

const Nav = styled.ul`
  display: flex;
  align-items: center;
  justify-content: space-between;
  border-bottom: 1px solid #343434;
  padding: 15px 55px;
`;

const NavItem = styled(Link)<NavItemProps>`
  font-size: 20px;
  color: ${DEFAULT_FONT_COLOR};
  cursor: pointer;

  &:hover {
    color: ${MAIN_COLOR};
  }

  ${props => props.$isActive && `color: ${MAIN_COLOR};`}
`;

```

**Comment by leesh2985** [comment]
넵 수정했습니다
