### ISSUE TITLE
vercel 배포 오류

### ISSUE THREAD

**Issue by leesh2985** [triptalk-4/triptalk-frontend#6]
배포 오류가 계속 생김 경로 오류 같은데 vs상에서는 오류가 따로 보이지 않음
![화면 캡처 2023-09-24 222634](https://github.com/triptalk-4/triptalk-frontend/assets/127204694/c0cd65cd-8239-4d8e-b451-6449f2da4544)
![화면 캡처 2023-09-24 222527](https://github.com/triptalk-4/triptalk-frontend/assets/127204694/047a2216-0259-40e6-93cc-08f646c10b41)
![화면 캡처 2023-09-24 222544](https://github.com/triptalk-4/triptalk-frontend/assets/127204694/29e94ebe-a060-4a91-8ef1-25c02cb2fe24)
![화면 캡처 2023-09-24 222558](https://github.com/triptalk-4/triptalk-frontend/assets/127204694/95f088c4-51f1-4f77-9f9d-d39b8e9e63a8)

**Comment by leesh2985** [comment]
절대경로 오류 일수있어서 절대경로도 설정해줌 해결 안됨

**Comment by oinochoe** [comment]
@leesh2985 해결되었나요? 어떻게 해결되었나요.

**Comment by leesh2985** [comment]
해결했습니다!
