### ISSUE TITLE
MSW 관련 질문

### ISSUE THREAD

**Issue by jin-park0115** [triptalk-4/triptalk-frontend#60]
저희가 지금 msw 작업을 하려고 하는데 폴더를 생성하고 폴더 안에 각각 데이터 파일들을 생성해야 하는 걸까요???

**Comment by leesh2985** [comment]
@oinochoe

**Comment by oinochoe** [comment]
@jin-park0115 @leesh2985 msw폴더를 따로 생성하고 그 안에서 데이터 관리하시면 좋겠네요 😃

**Comment by leesh2985** [comment]
넵!

**Comment by jin-park0115** [comment]
아하 넵 감사합니다!😆
